# Generated by Django 5.0.3 on 2024-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('hotel', 'Hotel')], default='user', max_length=10),
        ),
    ]
