# Generated by Django 5.0.3 on 2024-03-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_booking',
        ),
    ]
