# Generated by Django 5.0.3 on 2024-03-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_remove_rating_item_remove_rating_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='item_name',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
    ]
