# Generated by Django 5.0.2 on 2024-03-22 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_rate_remove_hotel_rating_and_more'),
        ('review', '0004_alter_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel.hotel'),
        ),
    ]
