# Generated by Django 5.0.3 on 2024-03-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_day',
            field=models.DateField(default='2024-01-05'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_day',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
