# Generated by Django 5.0.3 on 2024-03-22 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_user_alter_appointment_hotel'),
        ('hotel', '0004_alter_hotel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
