# Generated by Django 5.0.3 on 2024-03-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single', 'Single Room'), ('Suite', 'Suite'), ('Family', 'Family Room')], default='Single', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.FloatField(default=1.0)),
                ('guest', models.IntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('address', models.CharField(max_length=255, null=True)),
                ('prices', models.FloatField(default=0.0)),
                ('rating', models.CharField(choices=[('⭐️', '1 Star'), ('⭐️⭐️', '2 Stars'), ('⭐️⭐️⭐️', '3 Stars'), ('⭐️⭐️⭐️⭐️', '4 Stars'), ('⭐️⭐️⭐️⭐️⭐️', '5 Stars')], default='⭐️', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Regected', 'Regected')], default='Pending', max_length=8)),
                ('description', models.TextField(null=True)),
                ('governorate', models.CharField(default='Unknown', max_length=101)),
                ('single_room', models.IntegerField(default=0)),
                ('suite', models.IntegerField(default=0)),
                ('family_room', models.IntegerField(default=0)),
                ('facility_desc', models.TextField(default='lorem Facility', max_length=1000)),
                ('facility', models.TextField(default='lorem Facility', max_length=1000)),
                ('is_tv', models.BooleanField(default=False)),
                ('is_wifi', models.BooleanField(default=False)),
                ('is_poll', models.BooleanField(default=False)),
                ('is_BreakFast', models.BooleanField(default=False)),
                ('is_Pet', models.BooleanField(default=False)),
                ('is_Accessibiliy', models.BooleanField(default=False)),
                ('is_Parking', models.BooleanField(default=False)),
            ],
        ),
    ]
