# Generated by Django 5.0.3 on 2024-03-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='review',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Pinding', 'Pinding'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='pinding', max_length=20),
        ),
    ]
