# Generated by Django 5.0.2 on 2024-03-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='review',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Regected', 'Regected')], default='Pending', max_length=8),
        ),
    ]
