# Generated by Django 5.0.3 on 2024-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facility',
            field=models.TextField(default='lorem Facility', max_length=1000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facility_desc',
            field=models.TextField(default='lorem Facility', max_length=1000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_Accessibiliy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_BreakFast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_Parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_Pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_poll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
