# Generated by Django 5.0.3 on 2024-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='map_location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
