# Generated by Django 5.0.3 on 2024-03-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_user_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
