# Generated by Django 5.0.3 on 2024-03-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('confirmed', 'confirmed')], default='pending', max_length=50),
        ),
    ]
