# Generated by Django 5.0.3 on 2024-03-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Pinding', 'Pinding'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='pinding', max_length=20),
        ),
    ]
