# Generated by Django 5.0.3 on 2024-03-18 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_address_hotel_description_hotel_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rate',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
