# Generated by Django 5.0.3 on 2024-03-18 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rate',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Okay', 'Okay'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='good', max_length=20),
        ),
    ]
