# Generated by Django 5.0.3 on 2024-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='family_room',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='single_room',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='suite',
            field=models.FloatField(default=0.0),
        ),
    ]
