# Generated by Django 5.0.3 on 2024-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_hotel_image_remove_hotel_prices_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
