# Generated by Django 5.0.3 on 2024-03-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_status'),
        ('hotel', '0007_alter_hotel_user'),
    ]

    operations = [
    ]
