# Generated by Django 5.0.3 on 2024-03-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_image_hotel_hotel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='prices',
            field=models.FloatField(default=0.0),
        ),
    ]
